# Generated by Django 3.2.1 on 2021-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.TextField()),
                ('fecha', models.TextField()),
                ('tiempoconectado', models.TextField()),
                ('fechaoff', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
