# Generated by Django 3.2.1 on 2021-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('inicoruta', models.CharField(blank=True, default='', max_length=100)),
                ('destino', models.TextField()),
                ('cliente', models.TextField()),
                ('tiempovuelo', models.TextField()),
                ('fechallegada', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
